table Dim_Calendario
	lineageTag: 9d396196-52e3-4d38-83c1-37aa358c2662

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 23892b3f-5356-4f9e-b0d2-fa23d0c390b9
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: e9733d22-c67f-4603-83cf-5c8c0d330a9e
			defaultHierarchy: LocalDateTable_b732d682-80f2-49ea-ba8d-f9af5c89801a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 61e8da8f-b017-4130-8cf0-c0962b3fe9fc
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: c4a52b0a-820c-4dc5-b5b4-7b330373526a
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: ae9754be-18bd-4e83-829f-f6dc66d6c220
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 25c9fe16-2003-4660-bf64-3948c916b841
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 17d3fef4-97ff-4dbf-8c15-42e9c0dfe1e7
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\DELL\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

