table fact_Presupuestos
	lineageTag: 1f1728cf-b258-439b-adb2-7dc3375e0b52

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: 708d3fd4-5079-4c7b-b6a1-87720fa5922e
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: string
		lineageTag: 3246b47c-5a1b-43ad-8246-d8b5ff9d8636
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: cbf94c55-58dc-4b5c-945c-072c62596c91
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: 7c3a0bf6-6e66-4d98-bd2d-fd913cbf2197
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	partition fact_Presupuestos = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\DELL\Downloads\VentasVehiculos.xlsx"), null, true),
				    fact_Presupuestos_Table = Origen{[Item="fact_Presupuestos",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(fact_Presupuestos_Table,{{"periodo", Int64.Type}, {"mes", type text}, {"id_sede", Int64.Type}, {"ppto", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

